### ISSUE TITLE
Compiling errors when using the command

### ISSUE THREAD

**Issue by WilliamWangPeng** [manuelliebchen/cuda-raytracer#1]
HI dear author,  
    It's truly a honor to write a letter to you,  I'm building your project nowadays and found the error when building as following, I wonder if there is a chance that you know the reason? :)

![image](https://user-images.githubusercontent.com/51076736/119220672-41a9eb80-bb1e-11eb-9f63-fb1cb11b28d5.png)

thank you  
best regards to you  
William

**Comment by manuelliebchen** [comment]
Hi there,
I'm very sorry to tell you that I can't get it to run on my side ether.
I pushed a few updates to make the code more readable.
It may be an error with the cuda device selection, I didn't implement any logic for that. 
Do you have a Nvidia Cuda divice?
Best Regards,
Manuel
